---
# The source code packaged with this file is Free Software, Copyright (C) 2016 by
# Unidad de Laboratorios, Escuela Politecnica Superior, Universidad de Alicante :: <aeps at eps.ua.es>.
# It's licensed under the AFFERO GENERAL PUBLIC LICENSE unless stated otherwise.
# You can get copies of the licenses here: http://www.affero.org/oagpl.html
# AFFERO GENERAL PUBLIC LICENSE is also included in the file called "LICENSE".


# All nodes except nonrpe Group 
- hosts: all:!nonrpe:!windows
  remote_user: ansible 
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - include: group_by.yml
  - include: pathFacts.yml

- hosts: all:!nonrpe:!windows
  gather_facts: False
  remote_user: ansible
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - nrpe

