#!/bin/sh
#
# Event handler script for starting the DNS servers
#
# Note: This script will only restart the server if the service is
#       retried 3 times (in a "soft" state) or if the service somehow
#       manages to fall into a "hard" error state.
#       
#
# What state is the service in?
case "$1" in
OK)
 	# The service just came back up, so don't do anything...
	;;
WARNING)
	# We don't really care about warning states, since the service
	# is probably still running...
	;;
UNKNOWN)
	# We don't know what might be causing an unknown error,
	# so don't do anything...
	;;
CRITICAL)
	# Aha!  The service appears to have a problem - perhaps we should
	# start the server...
	
	# Is this a "soft" or a "hard" state?
	case "$2" in
					
	# We're in a "soft" state, meaning that Nagios is in the middle of retrying the
	# check before it turns into a "hard" state and contacts get notified...
	SOFT)
		# What check attempt are we on?  We don't want to restart the
		# server on the first  check, because it may just be a fluke!
		case "$3" in
	
			# Wait until the check has been tried 3 times before restarting the server.
			# If the check fails on the 4th time (after we restart the server), the state
			# type will turn to "hard" and contacts will be notified of the problem.
			# Hopefully this will restart the server successfully, so the 4th check
			# will result in a "soft" recovery.
			# If that happens no one gets notified because we fixed the problem!
			3)
				echo -n "Starting DNS service in $4 (3rd soft critical state)..."							
				# Call the init script to start the server
				/usr/lib/nagios/plugins/check_nrpe -H "$4" -c restart-dns				
				;;
		esac
		;;
		# The service somehow managed to turn into a hard error without getting fixed.
		# It should have been restarted by the code above, but for some reason it didn't.
		# Let's give it one last try, shall we?  
		# Note: Contacts have already been notified of a problem with the service at this
		# point (unless you disabled notifications for this service)
	HARD)
		echo -n "Starting DNS service in $4..."
		# Call the script to start the server
		/usr/lib/nagios/plugins/check_nrpe -H "$4" -c restart-dns
		;;
	esac
	;;
esac
exit 0
