---
# The source code packaged with this file is Free Software, Copyright (C) 2016 by
# Unidad de Laboratorios, Escuela Politecnica Superior, Universidad de Alicante :: <aeps at eps.ua.es>.
# It's licensed under the AFFERO GENERAL PUBLIC LICENSE unless stated otherwise.
# You can get copies of the licenses here: http://www.affero.org/oagpl.html
# AFFERO GENERAL PUBLIC LICENSE is also included in the file called "LICENSE".


# DHCP service 

- include: dhcpP1.yml 
  tags: [ dhcp, P1 ]
  when: inventory_hostname in groups.P1
- include: dhcpP2.yml 
  tags: [ dhcp, P2 ]
  when: inventory_hostname in groups.P2
- include: dhcpP2.yml
  tags: [ dhcp, P3 ]
  when: inventory_hostname in groups.P3
