---
# The source code packaged with this file is Free Software, Copyright (C) 2016 by
# It's licensed under the AFFERO GENERAL PUBLIC LICENSE unless stated otherwise.
# You can get copies of the licenses here: http://www.affero.org/oagpl.html
# AFFERO GENERAL PUBLIC LICENSE is also included in the file called "LICENSE".


# nvi installation 

- name: Get python version
  shell: echo {{ ansible_python_version }}|cut -d' ' -f2|cut -d'.' -f1,2
  register: pythonVersion
  changed_when: False

- name: Be sure nvi is installed (Debian and python >= 2.6)
  apt: pkg=nvi state=installed force=yes
  when: ansible_pkg_mgr == "apt" and pythonVersion.stdout|float >= 2.6

- name: Be sure nvi is installed (Debian and python < 2.6)
  #shell: apt-get -y --force-yes install nvi 
  shell: ((apt-cache pkgnames|grep "^nvi$") >/dev/null && echo "No") || ((apt-get -y --force-yes install nvi) && echo "Changed") executable="/bin/bash"
  register: installDebian
  changed_when: installDebian.stdout == "Changed"
  when: ansible_pkg_mgr == "apt" and pythonVersion.stdout|float < 2.6

- name: Enlazar vi -> nvi (Debian)
  file: path=/usr/bin/vi state=link src=/usr/bin/nvi force=yes
  when: ansible_os_family == "Debian"
