---
# The source code packaged with this file is Free Software, Copyright (C) 2016 by
# Unidad de Laboratorios, Escuela Politecnica Superior, Universidad de Alicante :: <aeps at eps.ua.es>.
# It's licensed under the AFFERO GENERAL PUBLIC LICENSE unless stated otherwise.
# You can get copies of the licenses here: http://www.affero.org/oagpl.html
# AFFERO GENERAL PUBLIC LICENSE is also included in the file called "LICENSE".


# PAM-Ldap configuration

- name: Get python version
  shell: echo {{ ansible_python_version }}|cut -d' ' -f2|cut -d'.' -f1,2
  register: pythonVersion
  changed_when: False

- name: Be sure pam-ldap is installed (Centos)
  yum: pkg={{ item }} state=installed
  with_items:
    - pam_ldap
    - nss-pam-ldapd
  when: ansible_pkg_mgr == "yum"

- name: Be sure pam-ldap is installed (Debian and python >= 2.6)
  apt: pkg={{ item }} state=installed force=yes
  with_items:
    - libpam-ldap
    - libnss-ldap
    - libpam-tmpdir
  when: ansible_pkg_mgr == "apt" and pythonVersion.stdout|float >= 2.6

- name: Be sure pam-ldap is installed (Debian and python < 2.6)
  #shell: apt-get -y --force-yes install {{ item }} 
  shell: ((apt-cache pkgnames|grep "^{{ item }}$") >/dev/null && echo "No") || ((apt-get -y --force-yes install {{ item }}) && echo "Changed") executable="/bin/bash"
  register: installDebian
  changed_when: installDebian.stdout == "Changed"
  with_items:
    - libpam-ldap
    - libnss-ldap
    - libpam-tmpdir
  when: ansible_pkg_mgr == "apt" and pythonVersion.stdout|float < 2.6

- name: Configure pam_ldap.conf file (not Ubuntu)
  template: src=etc/pam_ldap.conf.{{ ansible_os_family }}.j2 dest=/etc/pam_ldap.conf owner=root group=root mode=0640
  register: pamldapConf
  when: ansible_distribution != "Ubuntu" 

- name: Configure ldap.conf file (Ubuntu)
  template: src=etc/ldap.conf.{{ ansible_distribution }}.j2 dest=/etc/ldap.conf owner=root group=root mode=0640
  register: ldapConf
  when: ansible_distribution == "Ubuntu"

- name: Configure nslcd.conf file (Centos)
  template: src=etc/nslcd.conf.j2 dest=/etc/nslcd.conf owner=root group=root mode=0600
  register: nslcdConf
  when: ansible_os_family == "RedHat"

- name: Configure libnss-ldap.conf file (Debian but not Ubuntu)
  template: src=etc/libnss-ldap.conf.j2 dest=/etc/libnss-ldap.conf owner=root group=root mode=0640
  register: libnssConf
  when: ansible_os_family == "Debian" and ansible_distribution != "Ubuntu"

- name: Configure nsswitch.conf file
  copy: src=etc/nsswitch.conf.{{ ansible_os_family }} dest=/etc/nsswitch.conf owner=root group=root mode=0644

- name: Configure system-auth & password-auth file (Centos)
  copy: src=etc/pam.d/{{ item }}.{{ ansible_os_family }} dest=/etc/pam.d/{{ item }} owner=root group=root mode=0644
  with_items: 
    - system-auth
    - password-auth
  when: ansible_os_family == "RedHat"

- name: Configure login (pam) file
  copy: src=etc/pam.d/login.{{ ansible_os_family }} dest=/etc/pam.d/login owner=root group=root mode=0644

- name: Configure passwd (pam) file
  copy: src=etc/pam.d/passwd.{{ ansible_os_family }} dest=/etc/pam.d/passwd owner=root group=root mode=0644

- name: Configure su (pam) file
  copy: src=etc/pam.d/su.{{ ansible_os_family }} dest=/etc/pam.d/su owner=root group=root mode=0644

- name: Get /etc/pam.d/ssh name
  shell: find /etc/pam.d/ -name "ssh*"|sort|head -1 executable="/bin/bash"
  register: sshPam 
  changed_when: False

- name: Configure ssh (pam) file
  copy: src=etc/pam.d/ssh.{{ ansible_os_family }} dest={{ sshPam.stdout }} owner=root group=root mode=0644
  when: sshPam.stdout|default("") != ""

- name: Getting Paths
  action: path_EPS
  changed_when: False
  ignore_errors: yes
  when: path.daemons.nslcd.name|default("") == "" or path.daemons.nscd.name|default("") == ""

- name: Restart nslcd (Centos) systemd
  systemd: name={{ path.daemons.nslcd.name }} state=restarted
  when: ansible_os_family == "RedHat" and path.daemons.nslcd.type == "systemctl" and path.daemons.nslcd.name != "" and nslcdConf|changed

- name: Restart nslcd (Centos) service
  service: name={{ path.daemons.nslcd.name }} state=restarted
  when: ansible_os_family == "RedHat" and path.daemons.nslcd.type == "service" and path.daemons.nslcd.name != "" and nslcdConf|changed

- name: Restart nslcd (Centos) init 
  shell: "{{ path.daemons.nslcd.name }} restart executable='/bin/bash'"
  when: ansible_os_family == "RedHat" and path.daemons.nslcd.type == "init" and path.daemons.nslcd.name != "" and nslcdConf|changed

- name: Restart nscd systemd
  systemd: name={{ path.daemons.nscd.name }} state=restarted
  when: path.daemons.nscd.type == "systemd" and path.daemons.nscd.name != "" and (pamldapConf|changed or ldapConf|changed or libnssConf|changed or nslcdConf|changed) 

- name: Restart nscd service
  service: name={{ path.daemons.nscd.name }} state=restarted
  when: path.daemons.nscd.type == "service" and path.daemons.nscd.name != "" and (pamldapConf|changed or ldapConf|changed or libnssConf|changed or nslcdConf|changed)

- name: Restart nscd init 
  shell: "{{ path.daemons.nscd.name }} restart executable='/bin/bash'"
  when: path.daemons.nscd.type == "init" and path.daemons.nscd.name != "" and (pamldapConf|changed or ldapConf|changed or libnssConf|changed or nslcdConf|changed) 

- name: Checking nslcd (Centos) systemd
  systemd: name={{ path.daemons.nslcd.name }} state=started enabled=true
  changed_when: False
  when: ansible_os_family == "RedHat" and path.daemons.nslcd.type == "systemctl" and path.daemons.nslcd.name != ""

- name: Checking nslcd (Centos) service
  service: name={{ path.daemons.nslcd.name }} state=started enabled=true
  changed_when: False
  when: ansible_os_family == "RedHat" and path.daemons.nslcd.type == "service" and path.daemons.nslcd.name != ""

- name: Checking nslcd (Centos) init
  shell: "{{ path.daemons.nslcd.name }} start; ([ \"{{ ansible_os_family }}\" == \"Debian\" ] && update-rc.d $(basename {{ path.daemons.nslcd.name }}) defaults) || ([ \"{{ ansible_os_family }}\" == \"RedHat\" ] && chkconfig $(basename {{ path.daemons.nslcd.name }}) on) executable='/bin/bash'"
  changed_when: False
  when: ansible_os_family == "RedHat" and path.daemons.nslcd.type == "init" and path.daemons.nslcd.name != ""

- name: Checking nscd systemd
  systemd: name={{ path.daemons.nscd.name }} state=started enabled=true
  changed_when: False
  when: path.daemons.nscd.type == "systemd" and path.daemons.nscd.name != ""

- name: Checking nscd service
  service: name={{ path.daemons.nscd.name }} state=started enabled=true
  changed_when: False
  when: path.daemons.nscd.type == "service" and path.daemons.nscd.name != ""

- name: Checking nscd init
  shell: "{{ path.daemons.nscd.name }} start; ([ \"{{ ansible_os_family }}\" == \"Debian\" ] && update-rc.d $(basename {{ path.daemons.nscd.name }}) defaults) || ([ \"{{ ansible_os_family }}\" == \"RedHat\" ] && chkconfig $(basename {{ path.daemons.nscd.name }}) on) executable='/bin/bash'"
  changed_when: False
  when: path.daemons.nscd.type == "init" and path.daemons.nscd.name != ""

