---
# The source code packaged with this file is Free Software, Copyright (C) 2016 by
# Unidad de Laboratorios, Escuela Politecnica Superior, Universidad de Alicante :: <aeps at eps.ua.es>.
# It's licensed under the AFFERO GENERAL PUBLIC LICENSE unless stated otherwise.
# You can get copies of the licenses here: http://www.affero.org/oagpl.html
# AFFERO GENERAL PUBLIC LICENSE is also included in the file called "LICENSE".


# syslog configuration 

- name: Find service binary
  shell: (((service --version || service --help || service) >/dev/null && echo "True") || echo "False") 2>/dev/null
  register: checkService
  changed_when: False

- name: Configure /etc/syslog.conf con lista syslog
  lineinfile: "name={{ syslogConf }} state=present regexp='{{ item.search }}' insertafter=EOF line='{{ item.replace }}'"
  register: syslogConfig
  with_items: "{{ syslog }}"

- name: Getting Service Name
  shell: ( echo "{{ path.daemons.syslog }}"|sed 's/.*\///' ) 2>/dev/null executable="/bin/bash"
  register: serviceName
  changed_when: False
  ignore_errors: yes
  when: checkService.stdout == "True" and path.daemons.syslog|default("") != ""

- name: Restart syslog service
  service: name={{ serviceName.stdout }} state=restarted enabled=true
  when: checkService.stdout == "True" and serviceName.stdout|default("") != "" and syslogConfig|changed

- name: Restart syslog daemon
  shell: '{{ path.daemons.syslog }} restart executable="/bin/bash"'
  when: checkService.stdout != "True" and syslogConfig|changed

