---
# The source code packaged with this file is Free Software, Copyright (C) 2016 by
# Unidad de Laboratorios, Escuela Politecnica Superior, Universidad de Alicante :: <aeps at eps.ua.es>.
# It's licensed under the AFFERO GENERAL PUBLIC LICENSE unless stated otherwise.
# You can get copies of the licenses here: http://www.affero.org/oagpl.html
# AFFERO GENERAL PUBLIC LICENSE is also included in the file called "LICENSE".


# syslog configuration 

- name: Get python version
  shell: echo {{ ansible_python_version }}|cut -d' ' -f2|cut -d'.' -f1,2
  register: pythonVersion
  changed_when: False

- name: Getting Paths
  action: path_EPS
  changed_when: False
  ignore_errors: yes
  when: path.daemons.syslog.name|default("") == ""

- name: Configure /etc/syslog.conf con lista syslog
  lineinfile: "name={{ syslogConf }} state=present regexp='{{ item.search }}' insertafter=EOF line='{{ item.replace }}'"
  register: syslogConfig
  with_items: "{{ syslog }}"

- name: Restart syslog systemd
  systemd: name={{ path.daemons.syslog.name }} state=restarted enabled=true
  when: path.daemons.syslog.type == "systemctl" and path.daemons.syslog.name != ""and syslogConfig|changed

- name: Restart syslog service
  service: name={{ path.daemons.syslog.name }} state=restarted enabled=true
  when: path.daemons.syslog.type == "service" and path.daemons.syslog.name != "" and syslogConfig|changed

- name: Restart syslog init 
  shell: '{{ path.daemons.syslog.name }} restart executable="/bin/bash"'
  when: path.daemons.syslog.type == "init" and path.daemons.syslog.name != "" and syslogConfig|changed

