---
# The source code packaged with this file is Free Software, Copyright (C) 2016 by
# Unidad de Laboratorios, Escuela Politecnica Superior, Universidad de Alicante :: <aeps at eps.ua.es>.
# It's licensed under the AFFERO GENERAL PUBLIC LICENSE unless stated otherwise.
# You can get copies of the licenses here: http://www.affero.org/oagpl.html
# AFFERO GENERAL PUBLIC LICENSE is also included in the file called "LICENSE".


# Munin (hosts file) configuration

- name: Copy hosts file to Munin Servers
  template: src=etc/munin/conf.d/hosts.j2 dest=/etc/munin/conf.d/hosts owner=root group=root mode=0644 backup=yes

